pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'server-portals'

includeBuild('libs/customportalapi') {
    dependencySubstitution {
        // When anything asks for net.kyrptonaught:customportalapi,
        // use the root project of the included build instead.
        substitute module('net.kyrptonaught:customportalapi') using project(':')
    }
}

includeBuild('../MC-Mods/Util-Mods/MC-Portal-Protocol')
