pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'server-portals'
includeBuild('../MC-Mods/Util-Mods/Authorization-Common')
include 'network-authorization'
project(':network-authorization').projectDir = file('../MC-Mods/Util-Mods/Network-Authorization/fabric')
